### ISSUE TITLE
Not working with `flake8==7.0.0` and `Python 3.11.7`

### ISSUE THREAD

**Issue by Danipulok** [rocioar/flake8-django#143]
Installed versions:
```
git+https://github.com/rocioar/flake8-django.git@895364969af49cbdd3c6ba8e63adeb9e4415ec5d#egg=flake8_django
flake8==7.0.0
```

Error:
```
$ flake8
Exception in thread Thread-3 (_handle_results):
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python311\Lib\multiprocessing\pool.py", line 579, in _handle_results
    task = get()
           ^^^^^
  File "C:\Program Files\Python311\Lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AstroidSyntaxError.__init__() missing 3 required positional arguments: 'modname', 'error', and 'path'
```

OS info:
```
OS: Windows
OS Release: 10
OS Version: 10.0.19045
Architecture: AMD64
Processor: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
Python Version: 3.11.7
```

But the same error was in python linux docker image: `python:3.11.7-bookworm@sha256:a2f76e7c73c241d15e867987f143dfbdcf280fb229ae1ecde98850504fd3b234`

**Comment by Danipulok** [comment]
Well, I hope everybody has moved to `ruff` already
